# 영화진흥위원회 오픈API

In [1]:
import requests
import pandas as pd
import time
import math

## 1. API 전체 목록 불러오기

In [2]:
# 여기에 발급받은 API 키를 입력하세요.
API_KEY = "0fedb3690ed2dbeb688fb9f77f9b7fdc"

# 영화 목록 API의 기본 URL
BASE_URL = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieList.json"

In [6]:
# 전체 영화 데이터를 저장할 리스트 초기화
all_movies_list = []

# 페이지 처리를 위한 변수 초기화
cur_page = 1
item_per_page = 100 # 한 페이지에 표시할 항목 수 (최대값으로 설정 권장)

print("영화 목록 데이터 추출을 시작합니다...")

while True:
    # API 요청에 필요한 파라미터 설정
    params = {
        'key': API_KEY,
        'curPage': str(cur_page),
        'itemPerPage': str(item_per_page),
    }

    try:
        # API 요청 보내기
        response = requests.get(BASE_URL, params=params)
        response.raise_for_status() # 오류가 발생하면 예외를 발생시킴

        # JSON 응답 파싱
        data = response.json()
        movie_list = data.get('movieListResult', {}).get('movieList', [])

        # 더 이상 가져올 영화 목록이 없으면 반복 종료
        if not movie_list:
            print("더 이상 가져올 데이터가 없어 추출을 종료합니다.")
            break

        # 현재 페이지의 영화 목록을 전체 리스트에 추가
        all_movies_list.extend(movie_list)

        print(f"페이지 {cur_page} 처리 완료 | 수집된 영화 수: {len(all_movies_list)}개")

        # 다음 페이지로 이동
        cur_page += 1

        # 서버 부하를 줄이기 위한 짧은 대기 시간
        time.sleep(0.5)

    except requests.exceptions.RequestException as e:
        print(f"API 요청 중 오류 발생: {e}")
        break
    except Exception as e:
        print(f"알 수 없는 오류 발생: {e}")
        break

print(f"\n총 {len(all_movies_list)}개의 영화 데이터를 성공적으로 수집했습니다.")

영화 목록 데이터 추출을 시작합니다...
페이지 1 처리 완료 | 수집된 영화 수: 100개
페이지 2 처리 완료 | 수집된 영화 수: 200개
페이지 3 처리 완료 | 수집된 영화 수: 300개
페이지 4 처리 완료 | 수집된 영화 수: 400개
페이지 5 처리 완료 | 수집된 영화 수: 500개
페이지 6 처리 완료 | 수집된 영화 수: 600개
페이지 7 처리 완료 | 수집된 영화 수: 700개
페이지 8 처리 완료 | 수집된 영화 수: 800개
페이지 9 처리 완료 | 수집된 영화 수: 900개
페이지 10 처리 완료 | 수집된 영화 수: 1000개
페이지 11 처리 완료 | 수집된 영화 수: 1100개
페이지 12 처리 완료 | 수집된 영화 수: 1200개
페이지 13 처리 완료 | 수집된 영화 수: 1300개
페이지 14 처리 완료 | 수집된 영화 수: 1400개
페이지 15 처리 완료 | 수집된 영화 수: 1500개
페이지 16 처리 완료 | 수집된 영화 수: 1600개
페이지 17 처리 완료 | 수집된 영화 수: 1700개
페이지 18 처리 완료 | 수집된 영화 수: 1800개
페이지 19 처리 완료 | 수집된 영화 수: 1900개
페이지 20 처리 완료 | 수집된 영화 수: 2000개
페이지 21 처리 완료 | 수집된 영화 수: 2100개
페이지 22 처리 완료 | 수집된 영화 수: 2200개
페이지 23 처리 완료 | 수집된 영화 수: 2300개
페이지 24 처리 완료 | 수집된 영화 수: 2400개
페이지 25 처리 완료 | 수집된 영화 수: 2500개
페이지 26 처리 완료 | 수집된 영화 수: 2600개
페이지 27 처리 완료 | 수집된 영화 수: 2700개
페이지 28 처리 완료 | 수집된 영화 수: 2800개
페이지 29 처리 완료 | 수집된 영화 수: 2900개
페이지 30 처리 완료 | 수집된 영화 수: 3000개
페이지 31 처리 완료 | 수집된 영화 수: 3100개
페이지 32 처리 완료 | 수집된 영화 수: 3200개
페이지 33 처리 완료 | 수집된 영화 수: 3300개
페이지 34 처리 완료 | 수집된 영화 수: 3400개
페이지 35 처리 완료 | 수집된 영화 수: 3500개
페이지 36 처리 완료 | 수집된 영화 수: 3600개
페이지 37 처리 완료 | 수집된 영화 수: 3700개
페이지 38 처리 완료 | 수집된 영화 수: 3800개
페이지 39 처리 완료 | 수집된 영화 수: 3900개
페이지 40 처리 완료 | 수집된 영화 수: 4000개
페이지 41 처리 완료 | 수집된 영화 수: 4100개
페이지 42 처리 완료 | 수집된 영화 수: 4200개
페이지 43 처리 완료 | 수집된 영화 수: 4300개
페이지 44 처리 완료 | 수집된 영화 수: 4400개
페이지 45 처리 완료 | 수집된 영화 수: 4500개
페이지 46 처리 완료 | 수집된 영화 수: 4600개
페이지 47 처리 완료 | 수집된 영화 수: 4700개
페이지 48 처리 완료 | 수집된 영화 수: 4800개
페이지 49 처리 완료 | 수집된 영화 수: 4900개
페이지 50 처리 완료 | 수집된 영화 수: 5000개
페이지 51 처리 완료 | 수집된 영화 수: 5100개
페이지 52 처리 완료 | 수집된 영화 수: 5200개
페이지 53 처리 완료 | 수집된 영화 수: 5300개
페이지 54 처리 완료 | 수집된 영화 수: 5400개
페이지 55 처리 완료 | 수집된 영화 수: 5500개
페이지 56 처리 완료 | 수집된 영화 수: 5600개
페이지 57 처리 완료 | 수집된 영화 수: 5700개
페이지 58 처리 완료 | 수집된 영화 수: 5800개
페이지 59 처리 완료 | 수집된 영화 수: 5900개
페이지 60 처리 완료 | 수집된 영화 수: 6000개
페이지 61 처리 완료 | 수집된 영화 수: 6100개
페이지 62 처리 완료 | 수집된 영화 수: 6200개
페이지 63 처리 완료 | 수집된 영화 수: 6300개
페이지 64 처리 완료 | 수집된 영화 수: 6400개
페이지 65 처리 완료 | 수집된 영화 수: 6500개
페이지 66 처리 완료 | 수집된 영화 수: 6600개
페이지 67 처리 완료 | 수집된 영화 수: 6700개
페이지 68 처리 완료 | 수집된 영화 수: 6800개
페이지 69 처리 완료 | 수집된 영화 수: 6900개
페이지 70 처리 완료 | 수집된 영화 수: 7000개
페이지 71 처리 완료 | 수집된 영화 수: 7100개
페이지 72 처리 완료 | 수집된 영화 수: 7200개
페이지 73 처리 완료 | 수집된 영화 수: 7300개
페이지 74 처리 완료 | 수집된 영화 수: 7400개
페이지 75 처리 완료 | 수집된 영화 수: 7500개
페이지 76 처리 완료 | 수집된 영화 수: 7600개
페이지 77 처리 완료 | 수집된 영화 수: 7700개
페이지 78 처리 완료 | 수집된 영화 수: 7800개
페이지 79 처리 완료 | 수집된 영화 수: 7900개
페이지 80 처리 완료 | 수집된 영화 수: 8000개
페이지 81 처리 완료 | 수집된 영화 수: 8100개
페이지 82 처리 완료 | 수집된 영화 수: 8200개
페이지 83 처리 완료 | 수집된 영화 수: 8300개
페이지 84 처리 완료 | 수집된 영화 수: 8400개
페이지 85 처리 완료 | 수집된 영화 수: 8500개
페이지 86 처리 완료 | 수집된 영화 수: 8600개
페이지 87 처리 완료 | 수집된 영화 수: 8700개
페이지 88 처리 완료 | 수집된 영화 수: 8800개
페이지 89 처리 완료 | 수집된 영화 수: 8900개
페이지 90 처리 완료 | 수집된 영화 수: 9000개
페이지 91 처리 완료 | 수집된 영화 수: 9100개
페이지 92 처리 완료 | 수집된 영화 수: 9200개
페이지 93 처리 완료 | 수집된 영화 수: 9300개
페이지 94 처리 완료 | 수집된 영화 수: 9400개
페이지 95 처리 완료 | 수집된 영화 수: 9500개
페이지 96 처리 완료 | 수집된 영화 수: 9600개
페이지 97 처리 완료 | 수집된 영화 수: 9700개
페이지 98 처리 완료 | 수집된 영화 수: 9800개
페이지 99 처리 완료 | 수집된 영화 수: 9900개
페이지 100 처리 완료 | 수집된 영화 수: 10000개
페이지 101 처리 완료 | 수집된 영화 수: 10100개
페이지 102 처리 완료 | 수집된 영화 수: 10200개
페이지 103 처리 완료 | 수집된 영화 수: 10300개
페이지 104 처리 완료 | 수집된 영화 수: 10400개
페이지 105 처리 완료 | 수집된 영화 수: 10500개
페이지 106 처리 완료 | 수집된 영화 수: 10600개
페이지 107 처리 완료 | 수집된 영화 수: 10700개
페이지 108 처리 완료 | 수집된 영화 수: 10800개
페이지 109 처리 완료 | 수집된 영화 수: 10900개
페이지 110 처리 완료 | 수집된 영화 수: 11000개
페이지 111 처리 완료 | 수집된 영화 수: 11100개
페이지 112 처리 완료 | 수집된 영화 수: 11200개
페이지 113 처리 완료 | 수집된 영화 수: 11300개
페이지 114 처리 완료 | 수집된 영화 수: 11400개
페이지 115 처리 완료 | 수집된 영화 수: 11500개
페이지 116 처리 완료 | 수집된 영화 수: 11600개
페이지 117 처리 완료 | 수집된 영화 수: 11700개
페이지 118 처리 완료 | 수집된 영화 수: 11800개
페이지 119 처리 완료 | 수집된 영화 수: 11900개
페이지 120 처리 완료 | 수집된 영화 수: 12000개
페이지 121 처리 완료 | 수집된 영화 수: 12100개
페이지 122 처리 완료 | 수집된 영화 수: 12200개
페이지 123 처리 완료 | 수집된 영화 수: 12300개
페이지 124 처리 완료 | 수집된 영화 수: 12400개
페이지 125 처리 완료 | 수집된 영화 수: 12500개
페이지 126 처리 완료 | 수집된 영화 수: 12600개
페이지 127 처리 완료 | 수집된 영화 수: 12700개
페이지 128 처리 완료 | 수집된 영화 수: 12800개
페이지 129 처리 완료 | 수집된 영화 수: 12900개
페이지 130 처리 완료 | 수집된 영화 수: 13000개
페이지 131 처리 완료 | 수집된 영화 수: 13100개
페이지 132 처리 완료 | 수집된 영화 수: 13200개
페이지 133 처리 완료 | 수집된 영화 수: 13300개
페이지 134 처리 완료 | 수집된 영화 수: 13400개
페이지 135 처리 완료 | 수집된 영화 수: 13500개
페이지 136 처리 완료 | 수집된 영화 수: 13600개
페이지 137 처리 완료 | 수집된 영화 수: 13700개
페이지 138 처리 완료 | 수집된 영화 수: 13800개
페이지 139 처리 완료 | 수집된 영화 수: 13900개
페이지 140 처리 완료 | 수집된 영화 수: 14000개
페이지 141 처리 완료 | 수집된 영화 수: 14100개
페이지 142 처리 완료 | 수집된 영화 수: 14200개
페이지 143 처리 완료 | 수집된 영화 수: 14300개
페이지 144 처리 완료 | 수집된 영화 수: 14400개
페이지 145 처리 완료 | 수집된 영화 수: 14500개
페이지 146 처리 완료 | 수집된 영화 수: 14600개
페이지 147 처리 완료 | 수집된 영화 수: 14700개
페이지 148 처리 완료 | 수집된 영화 수: 14800개
페이지 149 처리 완료 | 수집된 영화 수: 14900개
페이지 150 처리 완료 | 수집된 영화 수: 15000개
페이지 151 처리 완료 | 수집된 영화 수: 15100개
페이지 152 처리 완료 | 수집된 영화 수: 15200개
페이지 153 처리 완료 | 수집된 영화 수: 15300개
페이지 154 처리 완료 | 수집된 영화 수: 15400개
페이지 155 처리 완료 | 수집된 영화 수: 15500개
페이지 156 처리 완료 | 수집된 영화 수: 15600개
페이지 157 처리 완료 | 수집된 영화 수: 15700개
페이지 158 처리 완료 | 수집된 영화 수: 15800개
페이지 159 처리 완료 | 수집된 영화 수: 15900개
페이지 160 처리 완료 | 수집된 영화 수: 16000개
페이지 161 처리 완료 | 수집된 영화 수: 16100개
페이지 162 처리 완료 | 수집된 영화 수: 16200개
페이지 163 처리 완료 | 수집된 영화 수: 16300개
페이지 164 처리 완료 | 수집된 영화 수: 16400개
페이지 165 처리 완료 | 수집된 영화 수: 16500개
페이지 166 처리 완료 | 수집된 영화 수: 16600개
페이지 167 처리 완료 | 수집된 영화 수: 16700개
페이지 168 처리 완료 | 수집된 영화 수: 16800개
페이지 169 처리 완료 | 수집된 영화 수: 16900개
페이지 170 처리 완료 | 수집된 영화 수: 17000개
페이지 171 처리 완료 | 수집된 영화 수: 17100개
페이지 172 처리 완료 | 수집된 영화 수: 17200개
페이지 173 처리 완료 | 수집된 영화 수: 17300개
페이지 174 처리 완료 | 수집된 영화 수: 17400개
페이지 175 처리 완료 | 수집된 영화 수: 17500개
페이지 176 처리 완료 | 수집된 영화 수: 17600개
페이지 177 처리 완료 | 수집된 영화 수: 17700개
페이지 178 처리 완료 | 수집된 영화 수: 17800개
페이지 179 처리 완료 | 수집된 영화 수: 17900개
페이지 180 처리 완료 | 수집된 영화 수: 18000개
페이지 181 처리 완료 | 수집된 영화 수: 18100개
페이지 182 처리 완료 | 수집된 영화 수: 18200개
페이지 183 처리 완료 | 수집된 영화 수: 18300개
페이지 184 처리 완료 | 수집된 영화 수: 18400개
페이지 185 처리 완료 | 수집된 영화 수: 18500개
페이지 186 처리 완료 | 수집된 영화 수: 18600개
페이지 187 처리 완료 | 수집된 영화 수: 18700개
페이지 188 처리 완료 | 수집된 영화 수: 18800개
페이지 189 처리 완료 | 수집된 영화 수: 18900개
페이지 190 처리 완료 | 수집된 영화 수: 19000개
페이지 191 처리 완료 | 수집된 영화 수: 19100개
페이지 192 처리 완료 | 수집된 영화 수: 19200개
페이지 193 처리 완료 | 수집된 영화 수: 19300개
페이지 194 처리 완료 | 수집된 영화 수: 19400개
페이지 195 처리 완료 | 수집된 영화 수: 19500개
페이지 196 처리 완료 | 수집된 영화 수: 19600개
페이지 197 처리 완료 | 수집된 영화 수: 19700개
페이지 198 처리 완료 | 수집된 영화 수: 19800개
페이지 199 처리 완료 | 수집된 영화 수: 19900개
페이지 200 처리 완료 | 수집된 영화 수: 20000개
페이지 201 처리 완료 | 수집된 영화 수: 20100개
페이지 202 처리 완료 | 수집된 영화 수: 20200개
더 이상 가져올 데이터가 없어 추출을 종료합니다.

총 20200개의 영화 데이터를 성공적으로 수집했습니다.

In [8]:
movie_data=pd.DataFrame(all_movies_list)

| 응답 필드 | 값 | 설명 |
|---|---|---|
| movieCd | 문자열 | 영화코드를 출력합니다. |
| movieNm | 문자열 | 영화명(국문)을 출력합니다. |
| movieNmEn | 문자열 | 영화명(영문)을 출력합니다. |
| prdtYear | 문자열 | 제작연도를 출력합니다. |
| openDt | 문자열 | 개봉일을 출력합니다. |
| typeNm | 문자열 | 영화유형을 출력합니다. |
| prdtStatNm | 문자열 | 제작상태를 출력합니다. |
| nationAlt | 문자열 | 제작국가(전체)를 출력합니다. |
| genreAlt | 문자열 | 영화장르(전체)를 출력합니다. |
| repNationNm | 문자열 | 대표 제작국가명을 출력합니다. |
| repGenreNm | 문자열 | 대표 장르명을 출력합니다. |
| directors | 문자열 | 영화감독을 나타냅니다. |
| peopleNm | 문자열 | 영화감독명을 출력합니다. |
| companys | 문자열 | 제작사를 나타냅니다. |
| companyCd | 문자열 | 제작사 코드를 출력합니다. |
| companyNm | 문자열 | 제작사명을 출력합니다. |

In [31]:
movie_data.head()

,movieCd,movieNm,movieNmEn,prdtYear,openDt,typeNm,prdtStatNm,nationAlt,genreAlt,repNationNm,repGenreNm,directors,companys
0,20172126,(100ft),(100ft),2016,,단편,기타,"한국,미국",기타,한국,기타,[{'peopleNm': '김민정'}],[]
1,20256927,포풍추영,The Shadow’s Edge,2025,20250920,장편,개봉예정,"홍콩,중국","액션,범죄",홍콩,액션,[{'peopleNm': '래리 양'}],[]
2,20192905,근본주의자,A Fundamentalist,2019,,장편,기타,한국,"코미디,드라마,가족,액션",한국,코미디,[{'peopleNm': '고봉수'}],"[{'companyCd': '20189602', 'companyNm': '고브로 필..."
3,20256401,우리 우린,,,,기타,개봉예정,한국,드라마,한국,드라마,[],[]
4,2025A015,혈전,To Live through Death,2024,,장편,기타,중국,액션,중국,액션,[],[]

## 2. 전체 데이터 저장 (전처리X)

In [32]:
movie_data.to_csv("movie_full_list.csv", index=False, encoding='utf-8-sig')

## 3. 전처리 진행

In [33]:
temp=movie_data.copy()

In [34]:
temp.isna().sum()

movieCd        0
movieNm        0
movieNmEn      0
prdtYear       0
openDt         0
typeNm         0
prdtStatNm     0
nationAlt      0
genreAlt       0
repNationNm    0
repGenreNm     0
directors      0
companys       0
dtype: int64

In [35]:
temp.replace({'':pd.NA}, inplace=True)

In [36]:
temp.isna().sum()

movieCd            0
movieNm            0
movieNmEn       7064
prdtYear         539
openDt         16959
typeNm           141
prdtStatNm       107
nationAlt        230
genreAlt         826
repNationNm      230
repGenreNm       880
directors          0
companys           0
dtype: int64

In [37]:
sorted(movie_data["prdtYear"].unique())

['',
 '1874',
 '1905',
 '1919',
 '1920',
 '1921',
 '1922',
 '1924',
 '1925',
 '1926',
 '1927',
 '1928',
 '1930',
 '1931',
 '1932',
 '1933',
 '1934',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1948',
 '1949',
 '1950',
 '1951',
 '1952',
 '1953',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '202',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025']

# 박스오피스 상위 10개 정보

In [39]:
BASE_URL1 = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json"

# 💡 조회하고 싶은 날짜를 'YYYYMMDD' 형식으로 바꾸면 됩니다.
# 여기서는 어제 날짜인 2025년 9월 6일로 설정했습니다.
target_dt = "20250906" 

# 3. API 요청 보내기
# 요청에 필요한 파라미터들을 딕셔너리 형태로 구성합니다.
params = {
    'key': API_KEY,
    'targetDt': target_dt,
    'itemPerPage': '100'  # 상위 10개 영화만 조회
}

try:
    # requests.get() 함수를 사용해 API에 GET 요청을 보냅니다.
    response = requests.get(BASE_URL1, params=params)
    response.raise_for_status() # HTTP 오류가 발생하면 예외를 일으킵니다.

    # 4. 응답 데이터 처리 (JSON -> Pandas DataFrame)
    # 응답받은 JSON 데이터를 파이썬 딕셔너리로 변환합니다.
    data = response.json()

    # 실제 박스오피스 목록 데이터만 추출합니다.
    movie_list = data['boxOfficeResult']['dailyBoxOfficeList']

    # 보기 편하도록 딕셔너리 리스트를 pandas DataFrame(표)으로 변환합니다.
    df = pd.DataFrame(movie_list)
    
    # 5. 결과 출력
    print(f"✅ {target_dt} 일별 박스오피스 TOP 10\n")
    
    # 필요한 컬럼만 선택하여 순서대로 정렬 후 출력할 수 있습니다.
    # 예: 순위, 영화명, 개봉일, 당일 관객수, 누적 관객수
    columns_to_show = ['rank', 'movieNm', 'openDt', 'audiCnt', 'audiAcc']
    display(df[columns_to_show])

except requests.exceptions.RequestException as e:
    print(f"❌ API 요청 중 오류가 발생했습니다: {e}")
except KeyError:
    # API 응답 구조가 예상과 다를 때를 대비한 예외 처리
    print("❌ 응답 데이터의 구조가 예상과 다릅니다. 'boxOfficeResult' 또는 'dailyBoxOfficeList' 키를 찾을 수 없습니다.")
except Exception as e:
    print(f"❌ 알 수 없는 오류가 발생했습니다: {e}")

✅ 20250906 일별 박스오피스 TOP 10

  rank            movieNm      openDt audiCnt  audiAcc
0    1   극장판 귀멸의 칼날: 무한성편  2025-08-22  218983  3777857
1    2        컨저링: 마지막 의식  2025-09-03   72216   178856
2    3            살인자 리포트  2025-09-05   60628    99499
3    4            F1 더 무비  2025-06-25   38659  4882629
4    5                좀비딸  2025-07-30   38414  5465908
5    6             첫사랑 엔딩  2025-08-27    9976    99131
6    7                투게더  2025-09-03    6046    24711
7    8  아기돼지 3형제: 도넛별 대모험  2025-09-04    4522     8560
8    9  긴키 지방의 어느 장소에 대하여  2025-08-13    3688   265588
9   10            킹 오브 킹스  2025-07-16    2531  1300750

| 응답 필드 | 값 | 설명 |
|---|---|---|
| boxofficeType | 문자열 | 박스오피스 종류를 출력합니다. |
| showRange | 문자열 | 박스오피스 조회 일자를 출력합니다. |
| rnum | 문자열 | 순번을 출력합니다. |
| rank | 문자열 | 해당일자의 박스오피스 순위를 출력합니다. |
| rankInten | 문자열 | 전일대비 순위의 증감분을 출력합니다. |
| rankOldAndNew | 문자열 | 랭킹에 신규진입여부를 출력합니다. "OLD" : 기존 , "NEW" : 신규 |
| movieCd | 문자열 | 영화의 대표코드를 출력합니다. |
| movieNm | 문자열 | 영화명(국문)을 출력합니다. |
| openDt | 문자열 | 영화의 개봉일을 출력합니다. |
| salesAmt | 문자열 | 해당일의 매출액을 출력합니다. |
| salesShare | 문자열 | 해당일자 상영작의 매출총액 대비 해당 영화의 매출비율을 출력합니다. |
| salesInten | 문자열 | 전일 대비 매출액 증감분을 출력합니다. |
| salesChange | 문자열 | 전일 대비 매출액 증감 비율을 출력합니다. |
| salesAcc | 문자열 | 누적매출액을 출력합니다. |
| audiCnt | 문자열 | 해당일의 관객수를 출력합니다. |
| audiInten | 문자열 | 전일 대비 관객수 증감분을 출력합니다. |
| audiChange | 문자열 | 전일 대비 관객수 증감 비율을 출력합니다. |
| audiAcc | 문자열 | 누적관객수를 출력합니다. |
| scrnCnt | 문자열 | 해당일자에 상영한 스크린수를 출력합니다. |
| showCnt | 문자열 | 해당일자에 상영된 횟수를 출력합니다. |

In [ ]:
df

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt
0,1,1,0,OLD,20253289,극장판 귀멸의 칼날: 무한성편,2025-08-22,2356068100,47.5,1226738820,108.6,40841075670,218983,118851,118.7,3777857,1566,5410
1,2,2,0,OLD,20256702,컨저링: 마지막 의식,2025-09-03,750593230,15.1,354979680,89.7,1833805020,72216,34019,89.1,178856,915,2211
2,3,3,0,OLD,20233039,살인자 리포트,2025-09-05,593808900,12.0,246524170,71,966203630,60628,24547,68,99499,752,2561
3,4,4,0,OLD,20254501,F1 더 무비,2025-06-25,389586510,7.9,214678590,122.7,52358699030,38659,21370,123.6,4882629,647,1343
4,5,5,0,OLD,20241941,좀비딸,2025-07-30,371569370,7.5,224421880,152.5,51791877450,38414,22783,145.8,5465908,754,1707
5,6,6,0,OLD,20256281,첫사랑 엔딩,2025-08-27,97001420,2.0,50450800,108.4,938674810,9976,5212,109.4,99131,273,381
6,7,7,0,OLD,20256071,투게더,2025-09-03,55155500,1.1,21909300,65.9,202727400,6046,2400,65.8,24711,227,530
7,8,8,9,OLD,20256741,아기돼지 3형제: 도넛별 대모험,2025-09-04,39876400,0.8,34428700,632,77399000,4522,3821,545.1,8560,261,294
8,9,9,0,OLD,20256701,긴키 지방의 어느 장소에 대하여,2025-08-13,38136000,0.8,19843820,108.5,2712139670,3688,1983,116.3,265588,142,188
9,10,10,15,OLD,20254275,킹 오브 킹스,2025-07-16,24189950,0.5,21449750,782.8,12270101226,2531,2171,603.1,1300750,86,89