In [1]:
import pandas as pd

In [2]:
movie_info = pd.read_csv("movie_info_data.csv", encoding="utf-8-sig")

In [3]:
movie_info = movie_info.iloc[:, [0,-7,-6,-5,-4,-3,-2,-1]]
movie_info.head()

                Movie_Title  genre1 genre2 genre3 genre4 genre5 genre6 genre7
0                     #살아있다     드라마    NaN    NaN    NaN    NaN    NaN    NaN
1                    #아이엠히어  멜로/로맨스    코미디    NaN    NaN    NaN    NaN    NaN
2                     #위왓치유   다큐멘터리    NaN    NaN    NaN    NaN    NaN    NaN
3  (여자)아이들 월드투어 [아이돌] 인 시네마      공연    NaN    NaN    NaN    NaN    NaN    NaN
4                    0.0MHz  공포(호러)    NaN    NaN    NaN    NaN    NaN    NaN

In [4]:
# 멀티핫인코딩을 위해 모든 장르 컬럼을 하나로 합친 후, 장르별로 멀티핫 벡터 생성
genres = movie_info[['genre1', 'genre2', 'genre3', 'genre4', 'genre5', 'genre6', 'genre7']]
genre_set = pd.unique(genres.values.ravel('K'))
genre_set = [g for g in genre_set if pd.notnull(g)]
# 각 영화의 장르를 멀티핫 벡터로 변환
movie_info['genre_multi_hot'] = genres.apply(
    lambda row: [int(g in row.values) for g in genre_set], axis=1
)

In [23]:
movie_info

,Movie_Title,genre1,genre2,genre3,genre4,genre5,genre6,genre7,genre_multi_hot
0,#살아있다,드라마,NaN,NaN,NaN,NaN,NaN,NaN,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,#아이엠히어,멜로/로맨스,코미디,NaN,NaN,NaN,NaN,NaN,"[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..."
2,#위왓치유,다큐멘터리,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,(여자)아이들 월드투어 [아이돌] 인 시네마,공연,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,0.0MHz,공포(호러),NaN,NaN,NaN,NaN,NaN,NaN,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...,...,...,...,...
4735,"힘을 내요, 미스터 리",코미디,드라마,NaN,NaN,NaN,NaN,NaN,"[1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..."
4736,힘을 낼 시간,드라마,NaN,NaN,NaN,NaN,NaN,NaN,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4737,힙노시스: LP 커버의 전설,다큐멘터리,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4738,힙노틱,SF,액션,NaN,NaN,NaN,NaN,NaN,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..."
4739,힛쳐,액션,범죄,스릴러,NaN,NaN,NaN,NaN,"[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, ..."

In [34]:
movie_info[["Movie_Title", "genre_multi_hot"]].to_csv("movie_genre_multi_hot.csv", index=False, encoding="utf-8-sig")